CREATE TABLE tbl_districts (
    district_id INT AUTO_INCREMENT PRIMARY KEY,
    district_name VARCHAR(255) NOT NULL,
    state_id INT,
    FOREIGN KEY (state_id) REFERENCES tbl_states(state_id)
);

-- Insert districts into tbl_districts

-- Andaman and Nicobar Islands (state_id = 1)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Andaman District', 1),
('Nicobar District', 1);

-- Andhra Pradesh (state_id = 2)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Anantapur', 2),
('Chittoor', 2),
('East Godavari', 2),
('Guntur', 2),
('Krishna', 2),
('Kurnool', 2),
('Nellore', 2),
('Prakasam', 2),
('Srikakulam', 2),
('Visakhapatnam', 2),
('Vizianagaram', 2),
('West Godavari', 2),
('YSR Kadapa', 2),
('Adilabad', 2),
('Bhadradri Kothagudem', 2),
('Hyderabad', 2),
('Jagtial', 2),
('Jangaon', 2),
('Jogulamba Gadwal', 2),
('Kamareddy', 2),
('Karimnagar', 2),
('Khammam', 2),
('Mahabubabad', 2),
('Mahbubnagar', 2),
('Mancherial', 2),
('Medak', 2),
('Medchal-Malkajgiri', 2),
('Nagarkurnool', 2),
('Nalgonda', 2),
('Nizamabad', 2),
('Peddapalli', 2),
('Rajanna Sircilla', 2),
('Ranga Reddy', 2),
('Sangareddy', 2),
('Wanaparthy', 2),
('Warangal', 2),
('Warangal (Rural)', 2),
('Warangal (Urban)', 2);

-- Arunachal Pradesh (state_id = 3)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Anjaw', 3),
('Changlang', 3),
('Dibang Valley', 3),
('East Kameng', 3),
('East Siang', 3),
('Kamle', 3),
('Kolasib', 3),
('Kurung Kumey', 3),
('Kra Daadi', 3),
('Lepa Rada', 3),
('Lower Dibang Valley', 3),
('Lower Siang', 3),
('Longding', 3),
('Lohit', 3),
('Namsai', 3),
('Papum Pare', 3),
('Siang', 3),
('Tawang', 3),
('Tirap', 3),
('Upper Siang', 3),
('Upper Subansiri', 3),
('West Kameng', 3),
('West Siang', 3);

-- Assam (state_id = 4)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Baksa', 4),
('Barpeta', 4),
('Biswanath', 4),
('Bongaigaon', 4),
('Cachar', 4),
('Charaideo', 4),
('Chirang', 4),
('Darrang', 4),
('Dhemaji', 4),
('Dhubri', 4),
('Dibrugarh', 4),
('Goalpara', 4),
('Golaghat', 4),
('Hailakandi', 4),
('Hojai', 4),
('Jorhat', 4),
('Kamrup', 4),
('Kamrup Metropolitan', 4),
('Karbi Anglong', 4),
('Karimganj', 4),
('Kokrajhar', 4),
('Lakhimpur', 4),
('Majuli', 4),
('Morigaon', 4),
('Nagaon', 4),
('Nalbari', 4),
('Dima Hasao', 4),
('Sivasagar', 4),
('Sonitpur', 4),
('South Salmara-Mankachar', 4),
('Tinsukia', 4),
('Udalguri', 4),
('West Karbi Anglong', 4);

-- Bihar (state_id = 5)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Araria', 5),
('Arwal', 5),
('Aurangabad', 5),
('Bagaha', 5),
('Bettiah', 5),
('Bhagalpur', 5),
('Bhojpur', 5),
('Buxar', 5),
('Darbhanga', 5),
('East Champaran', 5),
('Gaya', 5),
('Gopalganj', 5),
('Jamui', 5),
('Jehanabad', 5),
('Kaimur', 5),
('Katihar', 5),
('Khagaria', 5),
('Kishanganj', 5),
('Lakhisarai', 5),
('Madhepura', 5),
('Madhubani', 5),
('Munger', 5),
('Muzaffarpur', 5),
('Nalanda', 5),
('Nawada', 5),
('Patna', 5),
('Purnia', 5),
('Rohtas', 5),
('Saran', 5),
('Samastipur', 5),
('Sheikhpura', 5),
('Sheohar', 5),
('Sitamarhi', 5),
('Supaul', 5),
('Vaishali', 5),
('West Champaran', 5);

-- Chandigarh (state_id = 6)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Chandigarh', 6);

-- Chhattisgarh (state_id = 7)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Balod', 7),
('Baloda Bazar', 7),
('Balrampur', 7),
('Bastar', 7),
('Bemetara', 7),
('Bijapur', 7),
('Bilaspur', 7),
('Dantewada (South Bastar)', 7),
('Dhamtari', 7),
('Durg', 7),
('Gariyaband', 7),
('Janjgir-Champa', 7),
('Jashpur', 7),
('Kabirdham (Kawardha)', 7),
('Kanker (North Bastar)', 7),
('Kondagaon', 7),
('Korba', 7),
('Koriya', 7),
('Mahasamund', 7),
('Mungeli', 7),
('Narayanpur', 7),
('Raigarh', 7),
('Raipur', 7),
('Rajnandgaon', 7),
('Sukma', 7),
('Surajpur', 7),
('Surguja', 7),
('Mungeli', 7),
('Janjgir-Champa', 7),
('Koriya', 7),
('Korba', 7),
('Raigarh', 7),
('Raipur', 7),
('Rajnandgaon', 7),
('Sukma', 7),
('Surajpur', 7),
('Surguja', 7);

-- Dadra and Nagar Haveli and Daman and Diu (state_id = 8)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Dadra and Nagar Haveli', 8),
('Daman', 8),
('Diu', 8);

-- Delhi (state_id = 9)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Central Delhi', 9),
('East Delhi', 9),
('New Delhi', 9),
('North Delhi', 9),
('North East Delhi', 9),
('North West Delhi', 9),
('South Delhi', 9),
('South East Delhi', 9),
('South West Delhi', 9),
('West Delhi', 9);

-- Goa (state_id = 10)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('North Goa', 10),
('South Goa', 10);

-- Gujarat (state_id = 11)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Ahmedabad', 11),
('Amreli', 11),
('Anand', 11),
('Aravalli', 11),
('Banaskantha', 11),
('Bharuch', 11),
('Bhavnagar', 11),
('Dahod', 11),
('Dang', 11),
('Gandhinagar', 11),
('Gir Somnath', 11),
('Jamnagar', 11),
('Junagadh', 11),
('Kutch', 11),
('Mehsana', 11),
('Narmada', 11),
('Navsari', 11),
('Panchmahal', 11),
('Patan', 11),
('Porbandar', 11),
('Rajkot', 11),
('Sabarkantha', 11),
('Surat', 11),
('Surendranagar', 11),
('Tapi', 11),
('Vadodara', 11),
('Valsad', 11);

-- Haryana (state_id = 12)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Ambala', 12),
('Bhiwani', 12),
('Charkhi Dadri', 12),
('Faridabad', 12),
('Fatehabad', 12),
('Gurugram', 12),
('Hisar', 12),
('Jind', 12),
('Jhajjar', 12),
('Jammu', 12),
('Karnal', 12),
('Kaithal', 12),
('Kurukshetra', 12),
('Mewat', 12),
('Panchkula', 12),
('Panipat', 12),
('Rewari', 12),
('Rohtak', 12),
('Sirsa', 12),
('Sonipat', 12),
('Yamunanagar', 12);

-- Himachal Pradesh (state_id = 13)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Bilaspur', 13),
('Chamba', 13),
('Hamirpur', 13),
('Kangra', 13),
('Kinnaur', 13),
('Kullu', 13),
('Lahul and Spiti', 13),
('Mandi', 13),
('Shimla', 13),
('Sirmaur', 13),
('Solan', 13),
('Una', 13);

-- Jharkhand (state_id = 14)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Bokaro', 14),
('Chatra', 14),
('Deoghar', 14),
('Dhanbad', 14),
('Dumka', 14),
('East Singhbhum', 14),
('Garhwa', 14),
('Giridih', 14),
('Godda', 14),
('Gumla', 14),
('Hazaribagh', 14),
('Jamtara', 14),
('Koderma', 14),
('Khunti', 14),
('Latehar', 14),
('Lohardaga', 14),
('Pakur', 14),
('Palamu', 14),
('Ranchi', 14),
('Sahebganj', 14),
('Seraikela-Kharsawan', 14),
('Simdega', 14),
('West Singhbhum', 14);

-- Karnataka (state_id = 15)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Bagalkot', 15),
('Bangalore Rural', 15),
('Bangalore Urban', 15),
('Belagavi', 15),
('Bellary', 15),
('Bidar', 15),
('Chamarajanagar', 15),
('Chickballapur', 15),
('Chikmagalur', 15),
('Chitradurga', 15),
('Dakshina Kannada', 15),
('Davangere', 15),
('Dharwad', 15),
('Gadag', 15),
('Hassan', 15),
('Haveri', 15),
('Kalaburagi', 15),
('Kodagu', 15),
('Kolar', 15),
('Koppal', 15),
('Mandya', 15),
('Mysuru', 15),
('Raichur', 15),
('Ramanagara', 15),
('Shimoga', 15),
('Tumakuru', 15),
('Udupi', 15),
('Uttar Kannada', 15),
('Vijayapura', 15),
('Vijayanagara', 15),
('Yadgir', 15);

-- Kerala (state_id = 16)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Alappuzha', 16),
('Ernakulam', 16),
('Idukki', 16),
('Kannur', 16),
('Kasaragod', 16),
('Kottayam', 16),
('Kollam', 16),
('Kozhikode', 16),
('Malappuram', 16),
('Palakkad', 16),
('Pathanamthitta', 16),
('Thiruvananthapuram', 16),
('Thrissur', 16),
('Wayanad', 16);

-- Ladakh (state_id = 17)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Leh', 17),
('Kargil', 17);

-- Lakshadweep (state_id = 18)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Agatti', 18),
('Amini', 18),
('Andrott', 18),
('Bangaram', 18),
('Bithra', 18),
('Kalapeni', 18),
('Kavaratti', 18),
('Kiltan', 18),
('Maliku', 18),
('Suheli', 18);

-- Madhya Pradesh (state_id = 19)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Agar Malwa', 19),
('Alirajpur', 19),
('Anuppur', 19),
('Ashok Nagar', 19),
('Balaghat', 19),
('Barwani', 19),
('Betul', 19),
('Bhind', 19),
('Bhopal', 19),
('Burhanpur', 19),
('Chhatarpur', 19),
('Chhindwara', 19),
('Damoh', 19),
('Datia', 19),
('Dewas', 19),
('Dhar', 19),
('Dindori', 19),
('Guna', 19),
('Gwalior', 19),
('Harda', 19),
('Hoshangabad', 19),
('Indore', 19),
('Jabalpur', 19),
('Jhabua', 19),
('Katni', 19),
('Khandwa', 19),
('Khargone', 19),
('Mandla', 19),
('Mandsaur', 19),
('Morena', 19),
('Narmadapuram', 19),
('Narsinghpur', 19),
('Neemuch', 19),
('Pachmarhi', 19),
('Panna', 19),
('Raisen', 19),
('Rajgarh', 19),
('Ratlam', 19),
('Rewa', 19),
('Sagar', 19),
('Satna', 19),
('Sehore', 19),
('Seoni', 19),
('Shahdol', 19),
('Shajapur', 19),
('Sheopur', 19),
('Shivpuri', 19),
('Sidhi', 19),
('Singrauli', 19),
('Tikamgarh', 19),
('Ujjain', 19),
('Umaria', 19),
('Vidisha', 19);

-- Maharashtra (state_id = 20)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Ahmednagar', 20),
('Akola', 20),
('Amravati', 20),
('Aurangabad', 20),
('Beed', 20),
('Bhandara', 20),
('Buldhana', 20),
('Chandrapur', 20),
('Dhule', 20),
('Gadchiroli', 20),
('Gondia', 20),
('Hingoli', 20),
('Jalgaon', 20),
('Jalna', 20),
('Kolhapur', 20),
('Latur', 20),
('Mumbai City', 20),
('Mumbai Suburban', 20),
('Nagpur', 20),
('Nanded', 20),
('Nandurbar', 20),
('Nashik', 20),
('Osmanabad', 20),
('Palghar', 20),
('Parbhani', 20),
('Pune', 20),
('Raigad', 20),
('Ratnagiri', 20),
('Satara', 20),
('Sindhudurg', 20),
('Solapur', 20),
('Thane', 20),
('Wardha', 20),
('Washim', 20),
('Yavatmal', 20);

-- Manipur (state_id = 21)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Bishnupur', 21),
('Chandel', 21),
('Churachandpur', 21),
('Imphal East', 21),
('Imphal West', 21),
('Jiribam', 21),
('Kakching', 21),
('Kamjong', 21),
('Kangpokpi', 21),
('Noney', 21),
('Senapati', 21),
('Tamenglong', 21),
('Tengnoupal', 21),
('Thoubal', 21),
('Ukhrul', 21);

-- Meghalaya (state_id = 22)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('East Garo Hills', 22),
('East Jaintia Hills', 22),
('East Khasi Hills', 22),
('North Garo Hills', 22),
('Ri-Bhoi', 22),
('South Garo Hills', 22),
('South West Garo Hills', 22),
('South West Khasi Hills', 22),
('West Garo Hills', 22),
('West Jaintia Hills', 22),
('West Khasi Hills', 22);

-- Mizoram (state_id = 23)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Aizawl', 23),
('Champhai', 23),
('Kolasib', 23),
('Lawngtlai', 23),
('Lunglei', 23),
('Mamit', 23),
('Saiha', 23),
('Serchhip', 23);

-- Nagaland (state_id = 24)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Dimapur', 24),
('Kiphire', 24),
('Kohima', 24),
('Longleng', 24),
('Mokokchung', 24),
('Mon', 24),
('Peren', 24),
('Phek', 24),
('Tuensang', 24),
('Wokha', 24),
('Zunheboto', 24);

-- Odisha (state_id = 25)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Angul', 25),
('Boudh', 25),
('Bargarh', 25),
('Balangir', 25),
('Balasore', 25),
('Bhadrak', 25),
('Bhubaneswar', 25),
('Cuttack', 25),
('Dhenkanal', 25),
('Ganjam', 25),
('Gajapati', 25),
('Jajpur', 25),
('Jagatsinghpur', 25),
('Jeypore', 25),
('Kalahandi', 25),
('Kandhamal', 25),
('Kendrapara', 25),
('Kendujhar', 25),
('Khurda', 25),
('Koraput', 25),
('Malkangiri', 25),
('Nabarangpur', 25),
('Nayagarh', 25),
('Nuapada', 25),
('Rayagada', 25),
('Sambalpur', 25),
('Subarnapur', 25),
('Sundargarh', 25);

-- Puducherry (state_id = 26)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Karaikal', 26),
('Mahe', 26),
('Puducherry', 26),
('Yanam', 26);

-- Punjab (state_id = 27)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Amritsar', 27),
('Barnala', 27),
('Bathinda', 27),
('Faridkot', 27),
('Fatehgarh Sahib', 27),
('Fazilka', 27),
('Ferozepur', 27),
('Gurdaspur', 27),
('Hoshiarpur', 27),
('Jalandhar', 27),
('Kapurthala', 27),
('Ludhiana', 27),
('Mansa', 27),
('Moga', 27),
('Muktsar', 27),
('Nawanshahr', 27),
('Pathankot', 27),
('Patiala', 27),
('Rupnagar', 27),
('Sangrur', 27),
('Sri Muktsar Sahib', 27),
('Tarn Taran', 27);

-- Rajasthan (state_id = 28)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Ajmer', 28),
('Alwar', 28),
('Banswara', 28),
('Baran', 28),
('Barmer', 28),
('Bhilwara', 28),
('Bikaner', 28),
('Bundi', 28),
('Chittorgarh', 28),
('Churu', 28),
('Dausa', 28),
('Dholpur', 28),
('Dungarpur', 28),
('Ganganagar', 28),
('Hanumangarh', 28),
('Jaipur', 28),
('Jaisalmer', 28),
('Jalore', 28),
('Jhalawar', 28),
('Jhunjhunu', 28),
('Jodhpur', 28),
('Karauli', 28),
('Nagaur', 28),
('Pali', 28),
('Rajasthan', 28),
('Sawai Madhopur', 28),
('Sikar', 28),
('Sirohi', 28),
('Tonk', 28),
('Udaipur', 28);

-- Sikkim (state_id = 29)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('East Sikkim', 29),
('North Sikkim', 29),
('South Sikkim', 29),
('West Sikkim', 29);

-- Tamil Nadu (state_id = 30)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Ariyalur', 30),
('Chengalpattu', 30),
('Chennai', 30),
('Coimbatore', 30),
('Cuddalore', 30),
('Dharmapuri', 30),
('Dindigul', 30),
('Erode', 30),
('Kallakurichi', 30),
('Kancheepuram', 30),
('Kanyakumari', 30),
('Karur', 30),
('Krishnagiri', 30),
('Madurai', 30),
('Nagapattinam', 30),
('Namakkal', 30),
('Nilgiris', 30),
('Perambalur', 30),
('Pudukkottai', 30),
('Ramanathapuram', 30),
('Salem', 30),
('Sivaganga', 30),
('Tenkasi', 30),
('Thanjavur', 30),
('Theni', 30),
('Thoothukudi', 30),
('Tiruchirappalli', 30),
('Tirunelveli', 30),
('Tirupathur', 30),
('Tirupur', 30),
('Tiruvallur', 30),
('Tiruvannamalai', 30),
('Vellore', 30),
('Viluppuram', 30),
('Virudhunagar', 30);

-- Telangana (state_id = 31)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Adilabad', 31),
('Bhadradri Kothagudem', 31),
('Hyderabad', 31),
('Jagtial', 31),
('Jangaon', 31),
('Jayashankar Bhupalapally', 31),
('Jogulamba Gadwal', 31),
('Kamareddy', 31),
('Karimnagar', 31),
('Khammam', 31),
('Mahabubabad', 31),
('Mahabubnagar', 31),
('Mancherial', 31),
('Medak', 31),
('Medchal-Malkajgiri', 31),
('Nagarkurnool', 31),
('Nalgonda', 31),
('Narayanpet', 31),
('Nirmal', 31),
('Nizamabad', 31),
('Peddapalli', 31),
('Rajanna Sircilla', 31),
('Ranga Reddy', 31),
('Sangareddy', 31),
('Vikarabad', 31),
('Warangal (Rural)', 31),
('Warangal (Urban)', 31),
('Yadadri Bhuvanagiri', 31);

-- Tripura (state_id = 32)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Ambassa', 32),
('Dhalai', 32),
('Khowai', 32),
('North Tripura', 32),
('Sepahijala', 32),
('South Tripura', 32),
('Unakoti', 32),
('West Tripura', 32);

-- Uttar Pradesh (state_id = 33)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Agra', 33),
('Aligarh', 33),
('Allahabad', 33),
('Ambedkar Nagar', 33),
('Amethi', 33),
('Amroha', 33),
('Auraiya', 33),
('Ayodhya', 33),
('Azamgarh', 33),
('Badaun', 33),
('Baghpat', 33),
('Bahraich', 33),
('Ballia', 33),
('Balrampur', 33),
('Banda', 33),
('Bangarmau', 33),
('Barabanki', 33),
('Bareilly', 33),
('Basti', 33),
('Bijnor', 33),
('Budaun', 33),
('Bulandshahr', 33),
('Chandauli', 33),
('Chitrakoot', 33),
('Deoria', 33),
('Etah', 33),
('Etawah', 33),
('Farrukhabad', 33),
('Fatehpur', 33),
('Firozabad', 33),
('Gautam Buddha Nagar', 33),
('Ghaziabad', 33),
('Ghazipur', 33),
('Gonda', 33),
('Gorakhpur', 33),
('Hamirpur', 33),
('Hardoi', 33),
('Hathras', 33),
('Jalaun', 33),
('Jaunpur', 33),
('Jhansi', 33),
('Kannauj', 33),
('Kanpur Dehat', 33),
('Kanpur Nagar', 33),
('Kasganj', 33),
('Kaushambi', 33),
('Kushinagar', 33),
('Lakhimpur Kheri', 33),
('Lalitpur', 33),
('Lucknow', 33),
('Maharajganj', 33),
('Mahoba', 33),
('Mainpuri', 33),
('Mathura', 33),
('Mau', 33),
('Meerut', 33),
('Mirzapur', 33),
('Moradabad', 33),
('Muzaffarnagar', 33),
('Pilibhit', 33),
('Pratapgarh', 33),
('Rae Bareli', 33),
('Rampur', 33),
('Saharanpur', 33),
('Sambhal', 33),
('Sant Kabir Nagar', 33),
('Sant Ravidas Nagar', 33),
('Shahjahanpur', 33),
('Shamli', 33),
('Shravasti', 33),
('Siddharthnagar', 33),
('Sitapur', 33),
('Sonbhadra', 33),
('Sultanpur', 33),
('Unnao', 33),
('Varanasi', 33);

-- Uttarakhand (state_id = 34)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Almora', 34),
('Bageshwar', 34),
('Bhilwara', 34),
('Chamoli', 34),
('Champawat', 34),
('Dehradun', 34),
('Haridwar', 34),
('Nainital', 34),
('Pauri Garhwal', 34),
('Pithoragarh', 34),
('Rudraprayag', 34),
('Tehri Garhwal', 34),
('Udham Singh Nagar', 34),
('Uttarkashi', 34);

-- West Bengal (state_id = 35)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Alipurduar', 35),
('Bankura', 35),
('Bardhaman', 35),
('Birbhum', 35),
('Cooch Behar', 35),
('Dakshin Dinajpur', 35),
('Darjeeling', 35),
('Hooghly', 35),
('Howrah', 35),
('Jalpaiguri', 35),
('Jhargram', 35),
('Kolkata', 35),
('Malda', 35),
('Murshidabad', 35),
('Nadia', 35),
('North 24 Parganas', 35),
('Purulia', 35),
('South 24 Parganas', 35),
('Uttar Dinajpur', 35);

-- Jammu and Kashmir (state_id = 36)
INSERT INTO tbl_districts (district_name, state_id) VALUES
('Anantnag', 36),
('Bandipora', 36),
('Baramulla', 36),
('Budgam', 36),
('Doda', 36),
('Ganderbal', 36),
('Jammu', 36),
('Kathua', 36),
('Kishtwar', 36),
('Kulgam', 36),
('Pulwama', 36),
('Ramban', 36),
('Reasi', 36),
('Samba', 36),
('Udhampur', 36),
('Jammu (Jammu)', 36),
('Kargil', 36),
('Leh', 36);
